package dmfmm.StarvationAhoy.Client.Renderer;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

/**
 * HTArmor - dmf444
 * Created using Tabula 4.1.1
 */
public class HTArmor extends ModelBiped {
    public double[] modelScale = new double[] { 3.0D, 3.0D, 3.0D };
    public ModelRenderer BackPlate;
    public ModelRenderer NeonPole;
    public ModelRenderer Reciever1;
    public ModelRenderer Reciever2;
    public ModelRenderer Reciever3;
    public ModelRenderer Reciever42;
    public ModelRenderer Reciever5;
    public ModelRenderer Reciever12;
    public ModelRenderer Reciever22;
    public ModelRenderer Reciever32;
    public ModelRenderer Reciever4;
    public ModelRenderer Reciever52;
    public ModelRenderer Connector1;
    public ModelRenderer Connector2;
    public ModelRenderer Connector3;
    public ModelRenderer Connector4;
    public ModelRenderer Connector5;
    public ModelRenderer Connector12;
    public ModelRenderer Connector22;
    public ModelRenderer Connector32;
    public ModelRenderer Connector42;
    public ModelRenderer Connector52;
    public ModelRenderer NeonPoleConnector;
    public ModelRenderer BackBelt;
    public ModelRenderer SideBelt1;
    public ModelRenderer SideFace2;
    public ModelRenderer FrontBelt1;
    public ModelRenderer FrontBelt2;
    public ModelRenderer FrontBeltButton;
    public ModelRenderer FrontBelt3;
    public ModelRenderer FrontBelt4;
    public ModelRenderer BackPlateSlope;
    public ModelRenderer FrontFace;
    public ModelRenderer SideBelt2;
    public ModelRenderer SideFace1;
    public ModelRenderer BackFace1;
    public ModelRenderer BackFace2;
    public ModelRenderer Connector32_1;
   // public ModelRenderer bipedHead;
   // public ModelRenderer bipedBody;

    public HTArmor() {
        this.textureWidth = 81;
        this.textureHeight = 81;
        this.FrontFace = new ModelRenderer(this, 0, 53);
        this.FrontFace.setRotationPoint(-0.4F, 0.0F, 5.6F);
        this.FrontFace.addBox(-12.1F, 0.0F, -12.0F, 25, 28, 0, 0.0F);
        this.bipedBody.addChild(FrontFace);
        this.Reciever12 = new ModelRenderer(this, 0, 45);
        this.Reciever12.setRotationPoint(-0.4F, 0.0F, 6.0F);
        this.Reciever12.addBox(-6.3F, 4.0F, 0.0F, 1, 2, 3, 0.0F);
        this.bipedBody.addChild(Reciever12);
        this.Connector42 = new ModelRenderer(this, 24, 33);
        this.Connector42.setRotationPoint(-0.4F, 0.0F, 6.5F);
        this.Connector42.addBox(-6.0F, 19.5F, 1.0F, 6, 1, 1, 0.0F);
        this.bipedBody.addChild(Connector42);
        this.FrontBelt1 = new ModelRenderer(this, 41, 26);
        this.FrontBelt1.setRotationPoint(-0.4F, 0.0F, 6.0F);
        this.FrontBelt1.addBox(-12.6F, 28.0F, -13.1F, 11, 5, 1, 0.0F);
        this.bipedBody.addChild(FrontBelt1);
        this.Connector3 = new ModelRenderer(this, 24, 33);
        this.Connector3.setRotationPoint(-0.4F, 0.0F, 6.5F);
        this.Connector3.addBox(0.8F, 14.5F, 1.0F, 6, 1, 1, 0.0F);
        this.bipedBody.addChild(Connector3);
      //  this.bipedHead = new ModelRenderer(this, 0, 0);
      //  this.bipedHead.setRotationPoint(0.0F, 0.0F, 0.0F);
     //   this.bipedHead.addBox(-4.0F, -8.0F, -4.0F, 8, 8, 8, 0.0F);
        this.Connector52 = new ModelRenderer(this, 24, 33);
        this.Connector52.setRotationPoint(-0.4F, 0.0F, 6.5F);
        this.Connector52.addBox(-6.0F, 24.5F, 1.0F, 6, 1, 1, 0.0F);
        this.bipedBody.addChild(Connector52);
        this.Connector5 = new ModelRenderer(this, 24, 33);
        this.Connector5.setRotationPoint(-0.4F, 0.0F, 6.5F);
        this.Connector5.addBox(0.8F, 24.5F, 1.0F, 6, 1, 1, 0.0F);
        this.bipedBody.addChild(Connector5);
        this.NeonPoleConnector = new ModelRenderer(this, 22, 33);
        this.NeonPoleConnector.setRotationPoint(-0.5F, 0.0F, 6.5F);
        this.NeonPoleConnector.addBox(0.0F, -0.8F, -1.5F, 1, 3, 1, 0.0F);
        this.setRotateAngle(NeonPoleConnector, 1.3203415791337103F, 0.0F, 0.0F);
        this.bipedBody.addChild(NeonPoleConnector);
        this.Reciever22 = new ModelRenderer(this, 0, 45);
        this.Reciever22.setRotationPoint(-0.4F, 0.0F, 6.0F);
        this.Reciever22.addBox(-6.3F, 9.0F, 0.0F, 1, 2, 3, 0.0F);
        this.bipedBody.addChild(Reciever22);
        this.BackPlateSlope = new ModelRenderer(this, 0, 26);
        this.BackPlateSlope.setRotationPoint(-4.3F, 26.7F, 5.9F);
        this.BackPlateSlope.addBox(0.0F, 0.0F, 0.0F, 9, 1, 1, 0.0F);
        this.setRotateAngle(BackPlateSlope, -0.31869712141416456F, 0.0F, 0.0F);
        this.bipedBody.addChild(BackPlateSlope);
        this.Connector4 = new ModelRenderer(this, 24, 33);
        this.Connector4.setRotationPoint(-0.4F, 0.0F, 6.5F);
        this.Connector4.addBox(0.8F, 19.5F, 1.0F, 6, 1, 1, 0.0F);
        this.bipedBody.addChild(Connector4);
        this.NeonPole = new ModelRenderer(this, 22, 26);
        this.NeonPole.setRotationPoint(-0.5F, 0.0F, 6.5F);
        this.NeonPole.addBox(0.0F, 1.0F, 1.0F, 1, 25, 1, 0.0F);
        this.bipedBody.addChild(NeonPole);
        this.FrontBelt4 = new ModelRenderer(this, 43, 28);
        this.FrontBelt4.setRotationPoint(-0.4F, 0.0F, 6.0F);
        this.FrontBelt4.addBox(-1.6F, 32.0F, -13.1F, 4, 1, 1, 0.0F);
        this.bipedBody.addChild(FrontBelt4);
        this.FrontBelt2 = new ModelRenderer(this, 41, 26);
        this.FrontBelt2.setRotationPoint(-0.4F, 0.0F, 6.0F);
        this.FrontBelt2.addBox(2.4F, 28.0F, -13.1F, 11, 5, 1, 0.0F);
        this.bipedBody.addChild(FrontBelt2);
        this.Connector32 = new ModelRenderer(this, 24, 33);
        this.Connector32.setRotationPoint(-0.4F, 0.0F, 6.5F);
        this.Connector32.addBox(-6.0F, 14.5F, 1.0F, 6, 1, 1, 0.0F);
        this.bipedBody.addChild(Connector32);
        this.SideFace1 = new ModelRenderer(this, 49, 40);
        this.SideFace1.setRotationPoint(-0.4F, 0.0F, 5.8F);
        this.SideFace1.addBox(-12.1F, 0.0F, -12.1F, 0, 28, 13, 0.0F);
        this.bipedBody.addChild(SideFace1);
        this.FrontBelt3 = new ModelRenderer(this, 43, 28);
        this.FrontBelt3.setRotationPoint(-0.4F, 0.0F, 6.0F);
        this.FrontBelt3.addBox(-1.6F, 28.0F, -13.1F, 4, 1, 1, 0.0F);
        this.bipedBody.addChild(FrontBelt3);
        this.Connector22 = new ModelRenderer(this, 24, 33);
        this.Connector22.setRotationPoint(-0.4F, 0.0F, 6.5F);
        this.Connector22.addBox(-6.0F, 9.5F, 1.0F, 6, 1, 1, 0.0F);
        this.bipedBody.addChild(Connector22);
        this.FrontBeltButton = new ModelRenderer(this, 56, 33);
        this.FrontBeltButton.setRotationPoint(-0.4F, 0.0F, 6.0F);
        this.FrontBeltButton.addBox(-1.6F, 29.0F, -12.5F, 4, 3, 1, 0.0F);
        this.bipedBody.addChild(FrontBeltButton);
        this.Reciever42 = new ModelRenderer(this, 0, 45);
        this.Reciever42.setRotationPoint(-0.4F, 0.0F, 6.0F);
        this.Reciever42.addBox(-6.3F, 19.0F, 0.0F, 1, 2, 3, 0.0F);
        this.bipedBody.addChild(Reciever42);
        this.Reciever1 = new ModelRenderer(this, 0, 45);
        this.Reciever1.setRotationPoint(-0.4F, 0.0F, 6.0F);
        this.Reciever1.addBox(6.3F, 4.0F, 0.0F, 1, 2, 3, 0.0F);
        this.bipedBody.addChild(Reciever1);
        this.BackFace2 = new ModelRenderer(this, 67, 25);
        this.BackFace2.setRotationPoint(-5.5F, 0.0F, 6.1F);
        this.BackFace2.addBox(-7.0F, 0.0F, 0.0F, 7, 28, 0, 0.0F);
        this.setRotateAngle(BackFace2, 0.0F, 0.091106186954104F, 0.0F);
        this.bipedBody.addChild(BackFace2);
        this.Reciever5 = new ModelRenderer(this, 0, 45);
        this.Reciever5.setRotationPoint(-0.4F, 0.0F, 6.0F);
        this.Reciever5.addBox(6.3F, 24.0F, 0.0F, 1, 2, 3, 0.0F);
        this.bipedBody.addChild(Reciever5);
      //  this.bipedBody = new ModelRenderer(this, 32, 0);
      //  this.bipedBody.setRotationPoint(0.0F, 0.0F, 0.0F);
      //  this.bipedBody.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4, 0.0F);
        this.Reciever52 = new ModelRenderer(this, 0, 45);
        this.Reciever52.setRotationPoint(-0.4F, 0.0F, 6.0F);
        this.Reciever52.addBox(-6.3F, 24.0F, 0.0F, 1, 2, 3, 0.0F);
        this.bipedBody.addChild(Reciever52);
        this.SideBelt2 = new ModelRenderer(this, 54, 7);
        this.SideBelt2.setRotationPoint(-0.4F, 0.0F, 5.8F);
        this.SideBelt2.addBox(12.4F, 28.0F, -12.0F, 1, 5, 12, 0.0F);
        this.bipedBody.addChild(SideBelt2);
        this.SideFace2 = new ModelRenderer(this, 49, 40);
        this.SideFace2.setRotationPoint(-0.4F, 0.0F, 5.8F);
        this.SideFace2.addBox(12.8F, 0.0F, -12.1F, 0, 28, 13, 0.0F);
        this.bipedBody.addChild(SideFace2);
        this.Reciever4 = new ModelRenderer(this, 0, 45);
        this.Reciever4.setRotationPoint(-0.4F, 0.0F, 6.0F);
        this.Reciever4.addBox(6.3F, 19.0F, 0.0F, 1, 2, 3, 0.0F);
        this.bipedBody.addChild(Reciever4);
        this.Connector2 = new ModelRenderer(this, 24, 33);
        this.Connector2.setRotationPoint(-0.4F, 0.0F, 6.5F);
        this.Connector2.addBox(0.8F, 9.5F, 1.0F, 6, 1, 1, 0.0F);
        this.bipedBody.addChild(Connector2);
        this.Connector12 = new ModelRenderer(this, 24, 33);
        this.Connector12.setRotationPoint(-0.4F, 0.0F, 6.5F);
        this.Connector12.addBox(-6.0F, 4.5F, 1.0F, 6, 1, 1, 0.0F);
        this.bipedBody.addChild(Connector12);
        this.BackPlate = new ModelRenderer(this, 0, 18);
        this.BackPlate.setRotationPoint(-0.4F, 0.0F, 5.8F);
        this.BackPlate.addBox(-3.9F, 2.0F, 0.0F, 9, 25, 1, 0.0F);
        this.bipedBody.addChild(BackPlate);
        this.Reciever32 = new ModelRenderer(this, 0, 45);
        this.Reciever32.setRotationPoint(-0.4F, 0.0F, 6.0F);
        this.Reciever32.addBox(-6.3F, 14.0F, 0.0F, 1, 2, 3, 0.0F);
        this.bipedBody.addChild(Reciever32);
        this.Connector32_1 = new ModelRenderer(this, 1, 33);
        this.Connector32_1.setRotationPoint(-0.4F, 0.0F, 6.5F);
        this.Connector32_1.addBox(-1.1F, 12.5F, -0.2F, 3, 1, 3, 0.0F);
        this.bipedBody.addChild(Connector32_1);
        this.SideBelt1 = new ModelRenderer(this, 54, 7);
        this.SideBelt1.setRotationPoint(-0.5F, 0.0F, 5.8F);
        this.SideBelt1.addBox(-12.5F, 28.0F, -12.0F, 1, 5, 12, 0.0F);
        this.bipedBody.addChild(SideBelt1);
        this.BackBelt = new ModelRenderer(this, 27, 18);
        this.BackBelt.setRotationPoint(-0.4F, 0.0F, 5.8F);
        this.BackBelt.addBox(-12.6F, 28.0F, 0.0F, 26, 5, 1, 0.0F);
        this.bipedBody.addChild(BackBelt);
        this.Connector1 = new ModelRenderer(this, 24, 33);
        this.Connector1.setRotationPoint(-0.4F, 0.0F, 6.5F);
        this.Connector1.addBox(0.8F, 4.5F, 1.0F, 6, 1, 1, 0.0F);
        this.bipedBody.addChild(Connector1);
        this.BackFace1 = new ModelRenderer(this, 67, 25);
        this.BackFace1.mirror = true;
        this.BackFace1.setRotationPoint(5.4F, 0.0F, 6.1F);
        this.BackFace1.addBox(0.0F, 0.0F, 0.0F, 7, 28, 0, 0.0F);
        this.setRotateAngle(BackFace1, 0.0F, -0.09075712110370514F, 0.0F);
        this.bipedBody.addChild(BackFace1);
        this.Reciever2 = new ModelRenderer(this, 0, 45);
        this.Reciever2.setRotationPoint(-0.4F, 0.0F, 6.0F);
        this.Reciever2.addBox(6.3F, 9.0F, 0.0F, 1, 2, 3, 0.0F);
        this.bipedBody.addChild(Reciever2);
        this.Reciever3 = new ModelRenderer(this, 0, 45);
        this.Reciever3.setRotationPoint(-0.4F, 0.0F, 6.0F);
        this.Reciever3.addBox(6.3F, 14.0F, 0.0F, 1, 2, 3, 0.0F);
        this.bipedBody.addChild(Reciever3);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) { 
        GL11.glPushMatrix();
        GL11.glScaled(1D / modelScale[0], 1D / modelScale[1], 1D / modelScale[2]);
        this.FrontFace.render(f5);
        this.Reciever12.render(f5);
        this.Connector42.render(f5);
        this.FrontBelt1.render(f5);
        this.Connector3.render(f5);
        this.Connector52.render(f5);
        this.Connector5.render(f5);
        this.NeonPoleConnector.render(f5);
        this.Reciever22.render(f5);
        this.BackPlateSlope.render(f5);
        this.Connector4.render(f5);
        this.NeonPole.render(f5);
        this.FrontBelt4.render(f5);
        this.FrontBelt2.render(f5);
        this.Connector32.render(f5);
        this.SideFace1.render(f5);
        this.FrontBelt3.render(f5);
        this.Connector22.render(f5);
        this.FrontBeltButton.render(f5);
        this.Reciever42.render(f5);
        this.Reciever1.render(f5);
        this.BackFace2.render(f5);
        this.Reciever5.render(f5);
        this.Reciever52.render(f5);
        this.SideBelt2.render(f5);
        this.SideFace2.render(f5);
        this.Reciever4.render(f5);
        this.Connector2.render(f5);
        this.Connector12.render(f5);
        this.BackPlate.render(f5);
        this.Reciever32.render(f5);
        this.Connector32_1.render(f5);
        this.SideBelt1.render(f5);
        this.BackBelt.render(f5);
        this.Connector1.render(f5);
        this.BackFace1.render(f5);
        this.Reciever2.render(f5);
        this.Reciever3.render(f5);
        GL11.glPopMatrix();
    }

    /**
     * This is a helper function from Tabula to set the rotation of model parts
     */
    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
